# Generated by Django 5.1.4 on 2024-12-28 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(help_text='Enter 11 digits Phone Number', max_length=11)),
                ('address', models.TextField()),
                ('gender', models.CharField(max_length=1)),
                ('state', models.CharField(choices=[('Sindh', 'Sindh'), ('Punjab', 'Punjab'), ('Balochistan', 'Balochistan'), ('KPK', 'KPK')], max_length=50)),
                ('prefered_location', models.CharField(choices=[('Karachi', 'Karachi'), ('Lahore', 'Lahore'), ('Islamabad', 'Islamabad'), ('Quetta', 'Quetta'), ('Peshawar', 'Peshawar'), ('Hyderabad', 'Hyderabad'), ('Sukkur', 'Sukkur'), ('Multan', 'Multan'), ('Faisalabad', 'Faisalabad'), ('Rawalpindi', 'Rawalpindi'), ('Gujranwala', 'Gujranwala'), ('Sialkot', 'Sialkot'), ('Bahawalpur', 'Bahawalpur'), ('Sargodha', 'Sargodha'), ('Sahiwal', 'Sahiwal'), ('Okara', 'Okara'), ('Wah', 'Wah'), ('Dera Ghazi Khan', 'Dera Ghazi Khan'), ('Mirpur Khas', 'Mirpur Khas'), ('Nawabshah', 'Nawabshah'), ('Mardan', 'Mardan'), ('Kasur', 'Kasur'), ('Sheikhupura', 'Sheikhupura'), ('Rahim Yar Khan', 'Rahim Yar Khan'), ('Gujrat', 'Gujrat'), ('Larkana', 'Larkana'), ('Jhang', 'Jhang'), ('Mingora', 'Mingora'), ('Narowal', 'Narowal'), ('Chiniot', 'Chiniot'), ('Kamoke', 'Kamoke'), ('Sukheke', 'Sukheke'), ('Hyderabad', 'Hyderabad'), ('Muzaffarabad', 'Muzaffarabad'), ('Mandi Bahauddin', 'Mandi Bahauddin'), ('Jhelum', 'Jhelum'), ('Khanpur', 'Khanpur'), ('Hafizabad', 'Hafizabad'), ('Kohat', 'Kohat'), ('Khuzdar', 'Khuzdar'), ('Dadu', 'Dadu'), ('Gojra', 'Gojra'), ('Muridke', 'Muridke'), ('Kohlu', 'Kohlu'), ('Jacobabad', 'Jacobabad'), ('Shikarpur', 'Shikarpur'), ('Kandhkot', 'Kandhkot'), ('Tando Allahyar', 'Tando Allahyar'), ('Dera Ismail Khan', 'Dera Ismail Khan'), ('Chaman', 'Chaman'), ('Hub', 'Hub'), ('Umerkot', 'Umerkot'), ('Dera Murad Jamali', 'Dera Murad Jamali'), ('Kotli', 'Kotli'), ('Dera Allah Yar', 'Dera Allah Yar'), ('Bhakkar', 'Bhakkar'), ('Turbat', 'Turbat'), ('Mianwali', 'Mianwali'), ('Chaman', 'Chaman'), ('Kharan', 'Kharan'), ('Wazirabad', 'Wazirabad')], max_length=250)),
                ('profile_image', models.ImageField(blank=True, upload_to='images/profile/')),
                ('resume_file', models.FileField(blank=True, upload_to='doc/resumes/')),
            ],
        ),
    ]
